### ISSUE TITLE
Examples and documentation

### ISSUE THREAD

**Issue by jimjamdev** [cartalyst/stripe-laravel#1]
I'm not finding much of anything is documentation and examples for Laravel 5.

Is there something being worked on, or am I missing it? All I see is https://cartalyst.com/manual/stripe/1.0#laravel

**Comment by brunogaspar** [comment]
Examples of what? 

The link you posted is just for the integration part on Laravel, the documentation [here](https://cartalyst.com/manual/stripe/1.0) covers pretty much everything you'll need.

**Comment by jimjamdev** [comment]
Maybe a small working example. It's quite difficult to read through that page and know if I'm doing it correctly. For example, I have everything set-up in composer, done the app/config and set my keys, But not sure where to go from here.

**Comment by brunogaspar** [comment]
Just read the documentation, it's all there buddy.

As stated at the end of [this page](https://cartalyst.com/manual/stripe-laravel/) you just need to swap `$stripe->` with `Stripe::` when using on Laravel, as you call the facade on Laravel, the rest is basically the same thing.

**Comment by jimjamdev** [comment]
Ok, seem to have it working ok. Turned out I had to do a composer dump-autoload and composer update.

Passing some mock data to stripe works. But I have one question.

I'm creating a refund from my admin panel and I'm reading this https://cartalyst.com/manual/stripe/1.0#refunds

I have a controller that i pass the data to from a form, but it doesn't seem to be picking up my parameters i.e.

``` php
$refund = Stripe::refunds()->create($stripe_order_id, [
                'amount' => '$amount',
                'reason' => $reason,
                'refund_application_fee' => true
]);
```

I've also tried 

``` php
$refund = Stripe::refunds()->create($stripe_order_id, [
            'parameters' => [
                'amount' => '$amount',
                'reason' => $reason,
                'refund_application_fee' => true
            ]

]);
```

But no luck. My array seems to miss the data I'm trying to pass

``` php
## Data Passed ##
ch_165KzrG7ZXaIAtn9oZ75BTXd, 100000, Customer requested refund

## Data from $refund array ##
Array
(
    [id] => re_167VZfG7ZXaIAtn96pE8OdZX
    [amount] => 100
    [currency] => gbp
    [created] => 1432837067
    [object] => refund
    [balance_transaction] => txn_167VZfG7ZXaIAtn9nnqvPVOj
    [metadata] => Array
        (
        )

    [charge] => ch_165KzrG7ZXaIAtn9oZ75BTXd
    [receipt_number] => 
    [reason] => 
)
```

Any idea what I'm doing wrong?

**Comment by brunogaspar** [comment]
You shouldn't pass the `'parameters' => [` bit, only the array itself

``` php
 [
    'amount' => '$amount',
    'reason' => $reason,
    'refund_application_fee' => true
]
```

**Comment by brunogaspar** [comment]
Companion methods:

```javascript```
dg.registerFilterPreset(:presetName, array :data);
dg.unregisterFilterPreset(:presetName);
```

**Comment by jimjamdev** [comment]
Man, you're quick :)

Is that not what I have in the first example?

**Comment by brunogaspar** [comment]
Not really though, you've this:

``` php
$refund = Stripe::refunds()->create($stripe_order_id, [
    'parameters' => [
        'amount' => '$amount',
        'reason' => $reason,
        'refund_application_fee' => true
    ]
]);
```

It should be this:

``` php
$refund = Stripe::refunds()->create($stripe_order_id, [
    'amount' => '$amount',
    'reason' => $reason,
    'refund_application_fee' => true
]);
```

I'll update the first example on the documentation to have this, as at the moment we only have on the update refund section.

**Comment by jimjamdev** [comment]
If you look at the very first code block I've posted, that's exactly what I have.
The one with the parameters was second :/

I've removed the ' ' from $amount in the array as well, so it's

``` php
$refund = Stripe::refunds()->create($stripe_order_id, [
                'amount' => $amount,
                'reason' => $reason,
                'refund_application_fee' => true
]);
```

Still no joy :(

**Comment by jimjamdev** [comment]
It's definitely passing the $stripe_order_id fine, but seems to be jumping to defaults for the rest of the info i.e.  [amount] => 100

**Comment by brunogaspar** [comment]
My test code:

``` php
Route::get('test', function ()
{
    $charge = Stripe::charges()->create([
        'amount'   => 100.00,
        'currency' => 'usd',
        'customer' => 'cus_64Pe4nfEwUEp7W'
    ]);

    $refund = Stripe::refunds()->create($charge['id'], [
        'amount' => 10.00,
        'reason' => 'requested_by_customer'
    ]);
});
```

It's working perfectly fine as you can see here http://d.pr/i/179h3 there is a refund of `10.00`.

**Comment by jimjamdev** [comment]
Weird, I'll spend some time with it, and see what I can find. Cheers for your help so far :)

**Comment by jimjamdev** [comment]
I shouldn't matter that I have this in a controller?

I'll try a test in the route.

**Comment by brunogaspar** [comment]
> I shouldn't matter that I have this in a controller?

It should be fine.

Forgot to paste the returned `$refund` object

``` php
array (size=10)
  'id' => string 're_167WmyJvzVWl1WTeQPqF5F1W' (length=27)
  'amount' => int 1000
  'currency' => string 'usd' (length=3)
  'created' => int 1432841736
  'object' => string 'refund' (length=6)
  'balance_transaction' => string 'txn_167WmyJvzVWl1WTe4NXrcNeZ' (length=28)
  'metadata' => 
    array (size=0)
      empty
  'charge' => string 'ch_167WmxJvzVWl1WTe1v5NrwDn' (length=27)
  'receipt_number' => null
  'reason' => string 'requested_by_customer' (length=21)
```

Let me know how it goes.

**Comment by jimjamdev** [comment]
Hmmm, I'm still getting the same thing with

``` php
Route::post('admin/orders/{id}/refund/process', function ()
{
    $stripe_order_id = Request::input('stripe_order_id');
    $amount = Request::input('refund_amount');
    $reason = Request::input('refund_reason');

    $refund = Stripe::refunds()->create($stripe_order_id, [
        'amount' => $amount,
        'refund_application_fee' => true
    ]);

    echo '<p>' . $stripe_order_id . ', ' . $amount . ', ' . $reason . '</p>';
    echo '<pre>'; print_r($refund); echo '</pre>';

});
```

in the route

**Comment by brunogaspar** [comment]
What's showing on Stripe end?

I can't reproduce this, as i've ran the snippet i posted earlier multiple times.

**Comment by jimjamdev** [comment]
Seems to be refunding fine minus the parameters

http://imgur.com/4iOHsVS

**Comment by brunogaspar** [comment]
What are you expecting to see there? Everything is working as expected.

**Comment by jimjamdev** [comment]
We'll I'm setting the refund amount to 200.00 here, but it's still passing 100

``` php
ch_165KzrG7ZXaIAtn9oZ75BTXd, 200.00, Customer requested refund

Array
(
    [id] => re_167YSGG7ZXaIAtn9K4xMgK4t
    [amount] => 100
    [currency] => gbp
    [created] => 1432848140
    [object] => refund
    [balance_transaction] => txn_167YSGG7ZXaIAtn9Bsqpc5Il
    [metadata] => Array
        (
        )

    [charge] => ch_165KzrG7ZXaIAtn9oZ75BTXd
    [receipt_number] => 
    [reason] => 
)
```

It's not picking up the reason either.

**Comment by brunogaspar** [comment]
I can't really reproduce this, sorry.

The refunds i create get created with the amount i give, no matter what, even the data i provide get's there, i just tested with the following:

``` php
$refund = Stripe::refunds()->create($charge['id'], [
    'amount' => 23.95,
    'reason' => 'requested_by_customer',
    'metadata' => [ 'foo' => 'Bar' ]
]);
```

And the charge http://d.pr/i/1cGw1 and the refund http://d.pr/i/13TAa and the response array http://d.pr/i/IgOA

Something on your end is causing this.

## 

I've tested with both Laravel 4 and Laravel 5.

Same results on both.

**Comment by jimjamdev** [comment]
Odd. It's just a default Laravel homestead setup.

I'll play around some more and see if I can track it down.

**Comment by brunogaspar** [comment]
@jimmyjamieson Try to place a `dd($parameters);` here https://github.com/cartalyst/stripe/blob/1.0/src/Api/Refunds.php#L36 and see what's the output.

**Comment by jimjamdev** [comment]
Yeah, my query params aren't coming through

http://imgur.com/HPcDPlp

**Comment by jimjamdev** [comment]
``` php
array:1 [▼
  "amount" => array:2 [▶]
]
```

**Comment by brunogaspar** [comment]
Something funky is going on there, the parameters you're passing are not reaching the package.

**Comment by brunogaspar** [comment]
And the `"amount"` is an array on your end for some reason.

**Comment by jimjamdev** [comment]
very wtf

**Comment by brunogaspar** [comment]
This is how it shows up on my end

``` php
array:3 [▼
  "amount" => 23.95
  "reason" => "requested_by_customer"
  "metadata" => array:1 [▼
    "foo" => "Bar"
  ]
]
```

**Comment by brunogaspar** [comment]
Can you try this on a clean Laravel 4/5 install?

**Comment by jimjamdev** [comment]
I can try yeah, though it is quite clean. Only started a few days ago

**Comment by jimjamdev** [comment]
Well, 6

**Comment by brunogaspar** [comment]
Just out of curiosity, can you click on the arrow that you have on the amount so i can see what's there?

**Comment by jimjamdev** [comment]
``` php
array:1 [▼
  "amount" => array:2 [▼
    "amount" => "200.00"
    "reason" => "requested_by_customer"
  ]
]
```

**Comment by brunogaspar** [comment]
Weird huh =)

**Comment by jimjamdev** [comment]
Very :)

**Comment by jimjamdev** [comment]
I'm wondering if another package could be the culprit

"require": {
        "laravel/framework": "5.0._",
        "doctrine/dbal": "^2.5",
        "illuminate/html": "^5.0",
        "cviebrock/eloquent-sluggable": "dev-master",
        "cartalyst/stripe-laravel": "2.0._"
    },

**Comment by brunogaspar** [comment]
Humm don't think so..

**Comment by jimjamdev** [comment]
I'm just setting up a clean installation of laravel to test

**Comment by brunogaspar** [comment]
I know what the issue, stupid me :(

I ran `composer update` on my Laravel 5 install, and i got the same output, so the issue is that we need to pass the `amount` as the second argument.

Like so:

``` php
$refund = Stripe::refunds()->create('ch_167YVUJvzVWl1WTe502Ri7DG', 23.95, [
    'reason' => 'requested_by_customer',
    'metadata' => [ 'foo' => 'Bar' ]
]);
```

The documentation wasn't updated to reflect this, will update them in a few.

Very sorry for the trouble.

**Comment by jimjamdev** [comment]
I'm actually laughing. I knew it would be something simple heh.

You've been a great help. It might be a good idea, when I finish this project to create a small sample on github for others to see how it works. Updating the docs would be good too :)

I'll delete this new laravel install and make the changes and see if it all works ok :)

**Comment by jimjamdev** [comment]
Though, how come it fails after a composer update?

**Comment by jimjamdev** [comment]
ahahaha, it works!!!! :)

**Comment by brunogaspar** [comment]
I had outdated dependencies on both apps apparently, hence i didn't noticed when i did the `dd($parameters);` but for the sake of debugging, i ran `composer update` to double check and it updated the Stripe package a few others, so it wasn't that outdated, but Stripe was one of them :(

After that, i looked into the code and yeap. I remember that i added the amount as an argument so it would be more easier to create refunds.

**Comment by jimjamdev** [comment]
Awesome. Well at least you know. I'm a pain but it helps :)

**Comment by JosephMendez** [comment]
what is The card unique identifier? is this the Token?  How do i get the cardID?

Retrieves the details of an existing credit card.

$card = $stripe->cards()->find('cus_4EBumIjyaKooft', 'card_4DmaB3muM8SNdZ');
