### ISSUE TITLE
Stripe::account()->create($account) failing

### ISSUE THREAD

**Issue by monove** [cartalyst/stripe-laravel#10]
I'm running `Stripe::account()->create($account)` in test mode with every possible field it could need, and I'm getting:

```
FatalErrorException in Handler.php line 123:
Call to undefined method Cartalyst\Stripe\Exception\ApiLimitExceededException::setErrorCode()
```

**Comment by brunogaspar** [comment]
Will push a fix for that exception in a few, but it seems that you have exceeded the api limit.

**Comment by brunogaspar** [comment]
Pushed a fix for that, give it a go and see if you receive the same error.
