### ISSUE TITLE
cartalyst/stripe v1.0.0 requires guzzlehttp/guzzle ~5.2

### ISSUE THREAD

**Issue by wkolcz** [cartalyst/stripe-laravel#11]
I have guzzlehttp/guzzle installed on my application (6.1,as a dependency of another package) and cartalyst/stripe-laravel will not install. I need cartalyst/stripe v1.0.0 installed which is asking for guzzlehttp/guzzle ~5.2

Any thoughts on how to get the 2 to play nice and allow me to install on my Laravel 5.1 application?

**Comment by GrahamCampbell** [comment]
Laravel 5.1 works fine with Guzzle 5. I personally ensured that it did.

**Comment by GrahamCampbell** [comment]
Note that Laravel 5.2 does not support guzzle 5. I removed the BC layer. Though, if you're not using any parts of Laravel that rely on guzzle, you can of course install any version. Laravel only suggests the guzzle version and does not enforce it.

**Comment by GrahamCampbell** [comment]
In terms of getting this library updated to Guzzle 6, I raised this issue a while back but my issue was closed :(

See https://github.com/cartalyst/stripe/issues/31.

**Comment by wkolcz** [comment]
I need 6 for another library so I guess the 2 are not compatible then with my application since it will not install with 6

**Comment by GrahamCampbell** [comment]
What library is that. Could it be easily modified to support guzzle 5 too?

**Comment by wkolcz** [comment]
neoxygen/neoclient. The application I am building is with Neo4j

**Comment by GrahamCampbell** [comment]
I've started https://github.com/cartalyst/stripe/pull/44.

**Comment by GrahamCampbell** [comment]
Version 2.x of neoxygen/neoclient support guzzle 5 btw.

**Comment by GrahamCampbell** [comment]
https://github.com/neoxygen/neo4j-neoclient/blob/2.2.10/composer.json

**Comment by wkolcz** [comment]
I'm sorry, I am not using an outdated library for my application to gain another library. I don't think versioning down one library for another is a solution.

**Comment by GrahamCampbell** [comment]
That's fine. I'm just offering a solution. It's basically that, or nothing at the moment.

**Comment by GrahamCampbell** [comment]
If you'd like to take over on my guzzle 6 upgrade PR, that's fine. Just let me know. I'm short on time so am unlikely to finish it quickly.

**Comment by wkolcz** [comment]
Thanks for the suggestion. What do you need to a guzzle 6 upgrade PR?
