### ISSUE TITLE
SKU price conversion disagrees with documentation.

### ISSUE THREAD

**Issue by CaffeinatedCodeMonkey** [cartalyst/stripe-laravel#13]
I'm using Laravel 5.2 with the appropriate stripe-laravel version, and have run into an issue. In the documentation it states that the price being passed for a SKU should be a positive integer representing the amount of the smallest currency unit. In my case, using USD, I would submit 100, which should be $1. However, the currency conversion in the package converted this to be $100, or 10000 cents. Any time I would pass an integer, I would consistently be submitting 100 times the price I intended. 

The conversion did work fine for a decimal, though the feature is undocumented.

**Comment by brunogaspar** [comment]
Feel free to submit a PR to update the documentation.
