### ISSUE TITLE
Issue with Billing Addon

### ISSUE THREAD

**Issue by ben-praveen** [cartalyst/stripe-laravel#16]

**Comment by brunogaspar** [comment]
?

**Comment by brunogaspar** [comment]
Closing due to the lack of description.

**Comment by cbj4074** [comment]
For some reason, the image came through in the notification email, but I don't see it here. Perhaps @iarjunphp solved his problem and deleted it.

The original image was:

![Original screenshot](https://cloud.githubusercontent.com/assets/5372754/14827615/dc290d3a-0c00-11e6-8647-387d6339a5f8.png)

**Comment by brunogaspar** [comment]
The Stripe Billing addon is only available to Cartalyst subscribers.

If he's not a subscriber, he'll not be able to install it.
