### ISSUE TITLE
Issue on exception handling

### ISSUE THREAD

**Issue by Raviideal01** [cartalyst/stripe-laravel#17]
Hello,

I am using laravel. We are unable to handle exception.

Here is my code 

try {
$card = $stripe->cards()->create('stripeid', [
            'number'    => '4242424242424242',
            'exp_month' => '05',
            'cvc'       => '123',
            'exp_year'  => '2018'
    ]);

} catch (Cartalyst\Stripe\Exception\NotFoundException $e) {
    $message = $e->getMessage(); 
}
 catch (Cartalyst\Stripe\Exception\BadRequestException $e) {
    $message = $e->getMessage(); 
}
 catch (Cartalyst\Stripe\Exception\InvalidRequestException $e) {
    $message = $e->getMessage(); 
}
 catch (Cartalyst\Stripe\Exception\CardErrorException $e) {
    $message = $e->getMessage(); 
}

 catch (Cartalyst\Stripe\Exception\NotFoundException $e) {
    $message = $e->getMessage(); 
}

What is wrong with code

**Comment by GrahamCampbell** [comment]
If you're working inside a namespace, you'll either need to import the exceptions classes, or put a leading slash before them, otherwise they'll be resolved as `App\Http\Controllers\Cartalyst\Stripe\Exception\NotFoundException`, or something like that.

**Comment by Raviideal01** [comment]
Thanks
Issue fixed.

I am trying to transfer fund to user. and i am getting error.
"Insufficient funds in Stripe account. In test mode, you can add funds to your available balance (bypassing your pending balance) by creating a charge with 4000 0000 0000 0077 as the card number. You can use the the /v1/balance endpoint to view your Stripe balance (for more details, see stripe.com/docs/api#balance)."

Do we have any exception handler for this.

**Comment by GrahamCampbell** [comment]
Seer https://github.com/cartalyst/stripe/issues/38. ;)

**Comment by Raviideal01** [comment]
Thanks Graham

**Comment by kaviexcel** [comment]
Hi,

I am using cartalyst stripe package for payment but i am unable to handle exception. I tried above methods.Still not able to handle exceptions.

Below is my code
     $stripe = new Stripe();
        $customer = $stripe->customers()->create([
             'email' => 'test@test.com',
        ]);
        try{
            $token = $stripe->tokens()->create([
                'card' => [
                    'number'    => '4242424242424242',
                    'exp_month' => 09,
                    'exp_year'  => 17,
                    'cvc'       => '3211',
                ],
            ]);
        }
        catch (App\Http\Controllers\Cartalyst\Stripe\Exception\CardErrorException $e) {
            $message = $e->getMessage();
            }
        catch (App\Http\Controllers\Cartalyst\Stripe\Exception\BadRequestException $e) {
            $message = $e->getMessage();
            }
        catch (App\Http\Controllers\Cartalyst\Stripe\Exception\InvalidRequestException $e) {
            $message = $e->getMessage();
            }
        catch (App\Http\Controllers\Cartalyst\Stripe\Exception\CardErrorException $e) {
            $message = $e->getMessage();
            }
        catch (App\Http\Controllers\Cartalyst\Stripe\Exception\NotFoundException $e) {
            $message = $e->getMessage();
            }


what's wrong with above code. I tried a lot but i can't.Kindly help me with some suggestions.

**Comment by brunogaspar** [comment]
@kaviexcel Please read https://github.com/cartalyst/stripe-laravel/issues/17#issuecomment-214996784

But basically, you're catching the exceptions incorrectly.

Try changing this

```php
catch (App\Http\Controllers\Cartalyst\Stripe\Exception\CardErrorException $e)
```

To this

```php
catch (\Cartalyst\Stripe\Exception\CardErrorException $e)
```

> Notice the leading slash (`\`)  at the beginning.

**Comment by kaviexcel** [comment]
Thanks a lot buddy. It's working.

**Comment by kaviexcel** [comment]
Hi ,
 How to handle insuffiecent amount exception in Cartalyst.

$charge = $stripe->charges()->create([
            'customer' => $customer['id'],
            'currency' => 'USD',
            'amount'   => "300"
        ]);

Help me with some ways to handle this.

**Comment by brunogaspar** [comment]
What's the exception and error it's throwing?

Failing to understand what's the issue.

**Comment by kaviexcel** [comment]
Hi,

I don't know how to put in sufficeint amount exception above charge creation.

**Comment by brunogaspar** [comment]
Sorry, but i'm not following what you're trying to achieve or the issue you're having.

**Comment by kaviexcel** [comment]
I'm trying to achieve an exception handling  when amount in the card is insufficient while charging.

**Comment by brunogaspar** [comment]
If there's something wrong with the card, the `CardErrorException` will be thrown with a message that Stripe itself returns, we don't control that.

**Comment by kaviexcel** [comment]
Buddy,

If the amount is insufficient in the card how can we handle that in exception.Because that CardErrorException will not handle the in-sufficient amount error right. Apologies if my understanding is wrong.

**Comment by brunogaspar** [comment]
As far as i know, Stripe doesn't return a specific error message for insufficient funds.
It just returns the generic `Your card was declined.` message.

With that said, you would only need to catch the `\Cartalyst\Stripe\Exception\CardErrorException` exception and retrieve the message they return using `$e->getMessage()`.

For more information, just reach out to the Stripe Support team and they will be able to enlighten you on this subject better than me, as what you want is out of the scope of this library, since we have no way to, **as far as i know**, to detect such error.

**Comment by GrahamCampbell** [comment]
> As far as i know, Stripe doesn't return a specific error message for insufficient funds.

It often does actually. Some banks just return a generic deline code though, preventing that.

**Comment by EduardoAlliance** [comment]
im unable to handle exception 

i try with
(\Cartalyst\Stripe\Exception\CardErrorException $e)
(CardErrorException $e)

my code:
use Cartalyst\Stripe\Stripe;
use Cartalyst\Stripe\Exception\CardErrorException;


 try {
                        $charge = $stripe->charges()->create([                       
                            'amount' => '1',
                            'currency' => 'USD',
                         'customer' => $user->customer_stripe
                        ]);

                        if($charge['status'] == 'succeeded'){
                            $status_succeeded = true;                         
                        }

                    }catch (CardErrorException $e){
                      $message =  $e->getMessage();
                      return redirect()->route('cart')
                    }

and throw error page 
local.ERROR: Your card does not support this type of purchase. {"userId":31,"exception":"[object] (Cartalyst\\Stripe\\Exception\\CardErrorException(code: 402): Your card does not support this type of purchase. at /home/web/appvendor/cartalyst/stripe/src/Exception/Handler.php:123)

edit:
 $charge = $stripe->charges()->create([                       
                            'amount' => '1',
                            'currency' => 'USD',
                            'description' => 'Order ' . $order->invoice_id,
                            'customer' => $user->customer_stripe                        
                        ]);
 if i try with    'customer' => $user->customer_stripe   get me error
 and if i use  'source' => $request->stripeToken  is working

**Comment by Krunal79-flutter** [comment]
> @kaviexcel Please read [#17 (comment)](https://github.com/cartalyst/stripe-laravel/issues/17#issuecomment-214996784)
> 
> But basically, you're catching the exceptions incorrectly.
> 
> Try changing this
> 
> ```
> catch (App\Http\Controllers\Cartalyst\Stripe\Exception\CardErrorException $e)
> ```
> 
> To this
> 
> ```
> catch (\Cartalyst\Stripe\Exception\CardErrorException $e)
> ```
> 
> > Notice the leading slash (`\`)  at the beginning.

Thank You Bro....... This Is Right Solution
