### ISSUE TITLE
Guzzle 6.0

### ISSUE THREAD

**Issue by ackerchez** [cartalyst/stripe-laravel#18]
The fact that the Laravel 5.1 version seems to require Guzzle 5.3 is causing problems for me. Any plans on updating the Guzzle version for the 3.0 Cartalyst version?

**Comment by brunogaspar** [comment]
We can probably bump the version of the cartalyst/stripe package to 2.0 since that version is already requiring Guzzle ~6.0.

**Comment by ackerchez** [comment]
Amazing! Any idea when to expect this?

**Comment by brunogaspar** [comment]
Give it a go by requiring:

```
"cartalyst/stripe-laravel": "~3.0@dev",
"guzzlehttp/guzzle": "~6.0"
```

I'll create a tag tomorrow.

**Comment by brunogaspar** [comment]
This is now done.

Related: a1dc5cb9e96bafdcf10fbdb706165717f1bc459f and 1a8962e0c83de6de3bf9b46f7a0458920d5a27fe
