### ISSUE TITLE
Bump version for Laravel 5.3

### ISSUE THREAD

**Issue by rossbearman** [cartalyst/stripe-laravel#20]
Can we get an official release that is compatible with Laravel 5.3? As far as I can tell it should just need the Laravel version bumped up in composer.json.

**Comment by GrahamCampbell** [comment]
v5 of this package is laravel 5.3 compatible. I've been using it for 6 weeks or so.

**Comment by rossbearman** [comment]
Yeah, just saw that the master branch is already set for 5.3, it just needs to be pushed out as a stable release.

**Comment by GrahamCampbell** [comment]
Well, it's still usable?

**Comment by rossbearman** [comment]
Absolutely, which is why it should probably get a stable release. :)

**Comment by GrahamCampbell** [comment]
For reference, here's an extract from an app of mine:

``` json
{
    ...
    "require": {
        "php": ">=7.0.0",
        "laravel/framework": "5.3.4",
        ...
        "cartalyst/stripe-laravel": "^5.0",
        ...
    },
    ...
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Means I don't need to care what stability my version constraints resolve too.

**Comment by rossbearman** [comment]
Of course, I'm already running it in the same manner since I noticed the release was available. And as happy as I am to use dev versions of packages, especially ones as simple as a Laravel wrapper, now that 5.3 is out and doesn't require any changes to this package, it would make sense for @brunogaspar to release the current master branch as it's been waiting for 5.3 to drop since January.

It just makes the package more usable for all if there's a stable release out and they don't have to go and check the issue queue to see if anyone is actually using it.

**Comment by brunogaspar** [comment]
Will do on monday!

**Comment by rossbearman** [comment]
Thanks @brunogaspar, have a good weekend.

**Comment by brunogaspar** [comment]
Done.
