### ISSUE TITLE
Use multiple Stripe accounts

### ISSUE THREAD

**Issue by ghost** [cartalyst/stripe-laravel#21]
I'm wanting to use this package rather than the native Stripe API that I'm currently using, but the problem is I have two Stripe accounts: one US-based and one UK-based.

My site deals with transactions for both accounts. How would I go about switching between them on a transaction-by-transaction basis?

Any advice much appreciated.

**Comment by brunogaspar** [comment]
Hello

You can most likely use the `setApiKey` [method](https://github.com/cartalyst/stripe/blob/2.0/src/Stripe.php#L119) and change the Stripe API Key whenever you need.
