### ISSUE TITLE
Laravel 5.4 Support

### ISSUE THREAD

**Issue by reganjohnson** [cartalyst/stripe-laravel#22]
Any plans for a release with support for Laravel 5.4?

**Comment by drsii** [comment]
Absolutely, we're not entirely sure how it will fall in the other 5.4 updates but we'll update this ticket when we know.

**Comment by brunogaspar** [comment]
Also check the `master` branch, it's already supported, just not tagged.

**Comment by brunogaspar** [comment]
Done.
