### ISSUE TITLE
Using Connect

### ISSUE THREAD

**Issue by kezern** [cartalyst/stripe-laravel#26]
I would like to use connect in stripe.
Create new accounts and connect them to my platform.
[https://stripe.com/docs/connect](https://stripe.com/docs/connect)
Is there any possibility with this library?

**Comment by brunogaspar** [comment]
Hello,

Yes that's possible.

Just use the `accountId()` method and pass the connected account id.

Example here: https://github.com/cartalyst/stripe/issues/74#issuecomment-254660176

Hope it answers your question.

**Comment by kezern** [comment]
I don't understand very well. I would like to create new connected accounts and manage payments to those accounts.

**Comment by brunogaspar** [comment]
To create new accounts to be managed by you it's simple

```php
$account = Stripe::account()->create([
    'managed' => true, // This is important and required
    'email' => $email,
    // pass other attributes here
]);

$accountId = $account['id'];
```

Now you have a connected account under your control and you can use the `$accountId` to retrieve that account id.

**Comment by kezern** [comment]
Thank you very much!, Now I have a connected account.
I couldn't find that method in the documentation. 
Could you tell me where I can find more info as others attributes I cant pass to the method?

Best regards!

**Comment by brunogaspar** [comment]
You can find this information, and more, on the official Stripe API documentation which is located [here](https://stripe.com/docs/api#create_account).
