### ISSUE TITLE
Updating a connected account

### ISSUE THREAD

**Issue by kezern** [cartalyst/stripe-laravel#27]
I have created a connected account setting managed attribute to true.
I can see It información my connected accounts list but stripe says i have to verify it using API.
How can I do that? Reading documentation i have found how to update charges. But not about accounts.

**Comment by brunogaspar** [comment]
```php
$accountId = 'the-account-id-here';

$verificationFile = __DIR__.'/path-to-some-file.jpg';

Stripe::account()->verify($accountId, $verificationFile, 'identity_document');
```

Hope it helps.

**Comment by kezern** [comment]
Thanks, one more question. I have to enter both sides of the id card. Only one image is entered in the example. How do I put the other one? Thank you

**Comment by brunogaspar** [comment]
I can be wrong, but as far as i know, Stripe only allows one file to be sent for account verification.

Our verify method is just a simple easy way to perform this action.

If a more custom request needs to be done, you'll can mimic what we're doing [here](https://github.com/cartalyst/stripe/blob/2.0/src/Api/Account.php#L101) and perform the file upload yourself using the API and then perform the account update.

**Comment by kezern** [comment]
Thanks! That works!!
Is there any doc where I can find this functions? I couldnt find the verify function. Now I need to accept terms for that account and I don't know how to do that.

**Comment by brunogaspar** [comment]
> Is there any doc where I can find this functions? I couldnt find the verify function.

It's not documented, only if you look into the source code at this moment :)

> Now I need to accept terms for that account and I don't know how to do that.

You'll need to perform an update on that account and pass an array with:

```php
Stripe::account()->update('account-id-here', [
    'tos_acceptance' => [
        'date' => 1504735739,
        'ip => '8.8.8.8',
    ],
]);
```

To find update parameters you can pass, it's always good to check the [Official Stripe API documentation](https://stripe.com/docs/api), for your case it's [here](https://stripe.com/docs/api#update_account).

Hope it helps.

**Comment by kezern** [comment]
Thank you very much!
Now I have to add external account to this account. I will try by my self.

Thanks again!
