### ISSUE TITLE
file upload does not work

### ISSUE THREAD

**Issue by deepakiapptech** [cartalyst/stripe-laravel#28]
there is no file upload section in cartalyst 
![2017-09-08-105404_1600x900_scrot](https://user-images.githubusercontent.com/17548634/30197230-228bb680-9484-11e7-8e2d-e61ca70e9254.png)

**Comment by brunogaspar** [comment]
Hello, it actually does work. Just not on the documentation.

You can have a look into the [tests](https://github.com/cartalyst/stripe/blob/2.0/tests/Api/FileUploadsTest.php) to see how they work.

**Comment by deepakiapptech** [comment]
thx it worked
