### ISSUE TITLE
what is The card unique identifier? is this the Token? How do i get the cardID?

### ISSUE THREAD

**Issue by JosephMendez** [cartalyst/stripe-laravel#30]
what is The card unique identifier? is this the Token? How do i get the cardID?

Retrieves the details of an existing credit card.

$card = $stripe->cards()->find('cus_4EBumIjyaKooft', 'card_4DmaB3muM8SNdZ');

**Comment by brunogaspar** [comment]
When you create a new card, you can retrieve it's id.

**Comment by JosephMendez** [comment]
thank you i got it
