### ISSUE TITLE
Get Stripe decline codes

### ISSUE THREAD

**Issue by ibarral** [cartalyst/stripe-laravel#34]
Hello,

If a card issuer declines a payment, Stripe provides some decline codes:

https://stripe.com/docs/declines/codes

Is there any way to get that codes?

Thanks!

**Comment by brunogaspar** [comment]
Hello,

If you've meant to say if that's possible to retrieve the code like `card_declined`, then yes, that's possible.

Example:

```php
try {
    $charge = Stripe::charges()->create([
        'currency' => 'USD',
        'amount'   => 123,45,
        'card'     => 'some-token',
    ]);
} catch (\Exception $e) {
   $errorCode = $e->getErrorCode();
}
```

If that's not what you're looking for, please elaborate a bit better.

Hope it helps!
