### ISSUE TITLE
What version of Stripe API is supported by this library?

### ISSUE THREAD

**Issue by seandelaney** [cartalyst/stripe-laravel#46]
I'm running:

- Laravel 5.7
- Cartalyst Stripe: 9.0.*
- Stripe API: 2019-02-19

However, when I follow the docs to create a subscription, I get an unknown `source` error. 

See: https://cartalyst.com/manual/stripe/2.0#create-a-subscription

Seems latest Stripe API docs no longer has a `source` field as a parameter.

See: https://stripe.com/docs/api/subscriptions/create

**Comment by brunogaspar** [comment]
Hello @seandelaney 

Yes, you're correct the default version is that the Stripe package uses is a bit outdated, i don't have an ETA to when i'll bump that version to the latest, but you can set the version you need by doing the following call:

```php
Stripe::setApiVersion('2019-02-19');
```

Or by setting it on your env & config file.

Doing this, you should technically be able you to use the majority of the endpoints (if not all), but do keep in mind that our documentation will not be in line with what Stripe requires, so you should consult their API documentation and see what you can pass and you cannot.

Let me know if you have more questions.
