### ISSUE TITLE
Are you going to update this package for matching SCA in September 2019?

### ISSUE THREAD

**Issue by ruchirkakkad** [cartalyst/stripe-laravel#48]
Starting in September 2019, a new regulation called Strong Customer Authentication (SCA) will require businesses in Europe to request additional authentication for online payments. The Payment Intents API fully supports SCA—including exemption logic—and ensure that you only ask customers to provide additional authentication when strictly necessary.

THE PAYMENT INTENTS API IS SCA-READY

https://stripe.com/docs/payments/payment-intents

Are you going to add this support in this package by anytime soon? Or if you have already prepared any other package for the same, can you please share the link?

Thanks!

**Comment by brunogaspar** [comment]
The package already has Payment Intents, it's just not documented :)

**Comment by behindyougmbh** [comment]
Does this also include Version 5?
If not, is the current version compatible with Laravel 5.3?

**Comment by brunogaspar** [comment]
> Does this also include Version 5?
> If not, is the current version compatible with Laravel 5.3?

As long as it uses the Cartalyst Stripe version 2, it does have that, so `stripe-laravel: ^5.0` is compatible.
