### ISSUE TITLE
Documentation for Payment intent

### ISSUE THREAD

**Issue by pazitron1** [cartalyst/stripe-laravel#49]
There does not seem to be documentation on how to use payment intent to comply with SCA. Or I missed it... Does it exist? It would help to understand how to make the Stripe integration SCA compliant. Thank you

**Comment by brunogaspar** [comment]
Hello, yes, documentation will be updated very soon to be in sync with Stripe API documentation itself.

**Comment by Harrrrry** [comment]
When and SCA available with 8.* version
