### ISSUE TITLE
"bindShared" is deprecated

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe-laravel#5]
It's been deprecated for a while, but was officially deprecated in 5.1 and was removed in 5.2.

Please use "singleton" instead.

I can send a PR after you've done the branch merge from our other PR @brunogaspar.

**Comment by GrahamCampbell** [comment]
Ping @brunogaspar. Please could you do a 1.0->2.0 branch merge.

**Comment by brunogaspar** [comment]
Merged.

**Comment by GrahamCampbell** [comment]
https://github.com/cartalyst/stripe-laravel/pull/6
