### ISSUE TITLE
v11.0.0 tag soon

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe-laravel#51]
Will there be a v11.0.0 tag soon? ;)

**Comment by brunogaspar** [comment]
After Laravel 6 release.

**Comment by GrahamCampbell** [comment]
Ok. Laravel 6 will be released on Tuesday. ;)

**Comment by brunogaspar** [comment]
Well, i can start doing some tags as i don't expect much more breaking changes to be done on Laravel 6, at least i hope so lol

**Comment by GrahamCampbell** [comment]
:P

**Comment by GrahamCampbell** [comment]
Historically, Laravel has done breaking changes even after a major release tag, so :trollface:

**Comment by brunogaspar** [comment]
This is now tagged.

**Comment by GrahamCampbell** [comment]
🎉
