### ISSUE TITLE
Is this package ready for Stripe's SCA?

### ISSUE THREAD

**Issue by ChristianGiupponi** [cartalyst/stripe-laravel#52]
Stripe is changing the payment methods introducing SCA: https://stripe.com/docs/strong-customer-authentication

Is this package ready?

**Comment by brunogaspar** [comment]
Yes.

https://github.com/cartalyst/stripe-laravel/search?q=sca&type=Issues
https://github.com/cartalyst/stripe/search?q=sca&type=Issues

**Comment by ChristianGiupponi** [comment]
Is it available even for the 9.x branch? I need to use it on Laravel 5.7

**Comment by brunogaspar** [comment]
Yes.

**Comment by Harrrrry** [comment]
Where I can check this is available in 8.* or it is available in 8.*

**Comment by brunogaspar** [comment]
There's no documentation on the Stripe package for this, but you can check the tests for the Payment Intents and Setup Intents on how to use it for the time being.
