### ISSUE TITLE
Can't find support for payment intent

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [cartalyst/stripe-laravel#54]
## Description
Stripe has integrated payment intents in order to be able to manage SCA, but it's needed some method from stripe api that i can't find on cartalyst.com like \Stripe\Paymentintent
I've searched all over the website but I wasn't able to find anything 

check: [here for the documentation which i'm referring to](https://stripe.com/docs/payments/payment-intents/web)

**Comment by brunogaspar** [comment]
https://github.com/cartalyst/stripe-laravel/search?q=payment+intent&type=Issues

Hope it helps.

**Comment by AlbertoSinigaglia** [comment]
so i just need to wait? thanks a lot, really... i know i'm asking maybe too much, but have you got any idea about how much there will be to wait? Only to understand if i need to proceed with stripe api or your amaizing package

**Comment by suwardany** [comment]
https://github.com/cartalyst/stripe-laravel/issues/52#issuecomment-530736204

The logic is already in place @AlbertoSinigaglia .. just no docs yet .. check out the `PaymentIntentTest` class for some usage examples.

**Comment by AlbertoSinigaglia** [comment]
oh, all right, thanks

**Comment by AlbertoSinigaglia** [comment]
and where is located that file?
founded, there was a missing 's'
thanks a lot
