### ISSUE TITLE
 The statement descriptor must be at most 22 characters

### ISSUE THREAD

**Issue by kevinmakwana** [cartalyst/stripe-laravel#56]
Cartalyst\Stripe\Exception\MissingParameterException  : The statement descriptor must be at most 22 characters. 1 year period with auto renew is 29 characters long.

**Comment by brunogaspar** [comment]
Not sure why you have opened this issue but it's not something the library can fix for you.

And according to the error, you'r passing a string which goes beyond the Stripe limit.

Here's documentation on how the Statement Descriptors work https://stripe.com/docs/statement-descriptors
