### ISSUE TITLE
Use STRIPE_KEY from database.

### ISSUE THREAD

**Issue by rtfmfm** [cartalyst/stripe-laravel#65]
Hello! Thank you for the package! It's very useful and saves me a lot of headaches. 
I'd like to be able to change Stripe Credentials from the web interface so I need to put them in the database and use them this way. Is it possible to achieve this with this package?

Thank you in advance!

**Comment by GrahamCampbell** [comment]
Yes, this is possible. You don't need this package. Just use the upstream stripe package.

**Comment by rtfmfm** [comment]
> Yes, this is possible. You don't need this package. Just use the upstream stripe package.

@GrahamCampbell, Thank you for your reply! Unfortunately I can not tell if it's irony, or answer that is trying to help me...

**Comment by GrahamCampbell** [comment]
I am being serious.

```bash
$ composer require cartalyst/stripe
```

```php
$client = new Cartalyst\Stripe\Stripe('YOUR-API-KEY', '2020-08-27');
```

**Comment by rtfmfm** [comment]
Thank you very much, @GrahamCampbell ! It worked!

**Comment by brunogaspar** [comment]
Thanks @GrahamCampbell
