### ISSUE TITLE
SCA not working

### ISSUE THREAD

**Issue by redlik** [cartalyst/stripe-laravel#67]
### Your Environment

- OS and Version: CentOS 7
- PHP Version: 7.3
- Stripe Laravel Version: 2.4.2

### Expected behaviour

Stripe SCA compliant payments

### Actual behaviour

All transactions are marked as not compliant, getting this message "Your account has payments (like this one) in live mode using the Charges API, which does not support the authentication requirements of SCA."

### Steps to reproduce

I've followed the official manual so not sure what's the issue, to be honest

**Comment by brunogaspar** [comment]
Hey

So, i've a personal application using this library, so i'm pretty sure it works and it's compliant :)

But to help you a bit, you can't use the Charges API (seems you're using it, but unsure from that message).

To be compliant, you should use the Payment Intents API or the Setup intents API.

Both APIs have different purposes and use cases:

- The Payment Intents is usually when the customer wants to pay you right way, like a one of charge.
- The Setup Intents is usually when the customer wants to pay you after, like an order on an e-commerce shop where you capture the card during fulfilment, which could be a few days after the order itself.

> Hopefully i explained it correctly.

But either way, this is explained on their official documentation, with fancy words too.

Sorry for being kinda brief and perhaps not helpful at all, but i can only offer support for the library itself and some bits of integrating it, the rest is really up to you to understand how Stripe works, which can be a tad challenging at first :)

All in all, the Stripe team are more than qualified (hopefully) to help you out on this, way better than myself :)

**Comment by redlik** [comment]
Thank you for all the tips. Much appreciated

Best regards,
Ralph
