### ISSUE TITLE
Minimum version for SCA compliant

### ISSUE THREAD

**Issue by atomos1** [cartalyst/stripe-laravel#69]
From which version cartalyst/stripe-laravel support SCA? 
Thanks

**Comment by brunogaspar** [comment]
For `cartalyst/stripe-laravel` is since `v3.0.0`, for `cartalyst/stripe` is since `v2.2.0`.

Hope it answers your question.

**Comment by atomos1** [comment]
Thank you Bruno,
but with ` "cartalyst/stripe-laravel": "7.0.*"` I get this error of `authentication_required`

What is causing this error if the library supports SCA?

Tested with a test card that triggers 3D Secure.

**Comment by brunogaspar** [comment]
Without seeing any code, is quite difficult to understand what might be wrong.

I recommend to read the official Stripe API Reference [here](https://stripe.com/docs/api) and see what parameters you can send through the payload, as you might be sending old parameters for the version your API Key is using.

**Comment by atomos1** [comment]
My code is actually this

```
$charge = Stripe::charges()->create([
    'customer' => $stripe_customer_id,
    'currency' => 'EUR',
    'capture' => false,
    'amount' => $price->getAmountDue(),
]);
```
(I capture the charge later)

According to stripe doc and also `cartalyst/stripe` (I assume is the same for `cartalyst/stripe-laravel`)  I need to completely change the workflow of payments switching to payments intents, right? 

e.g.
```
$paymentIntent = $stripe->paymentIntents()->create([
    'amount' => 2000,
    'currency' => 'usd',
    'payment_method_types' => [
        'card',
    ],
]);
```

I also assume that cartalyst/stripe-laravel v7 support intents.
