### ISSUE TITLE
Question About Branches

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe-laravel#7]
Aliasing your master to 2.0 and having a 2.0 branch as well is wrong surely? What does composer even do for working out which branch is wanted for `2.0.*@dev`?

**Comment by GrahamCampbell** [comment]
Also, when will the recent changes on 2.0 make it to the master branch?

**Comment by brunogaspar** [comment]
Will push it later, don't worry about it.

**Comment by GrahamCampbell** [comment]
Thanks. :)
