### ISSUE TITLE
Coupon Code Calculations

### ISSUE THREAD

**Issue by TheDoctorD** [cartalyst/stripe-laravel#72]
Should I be calculating the percentage off myself, or is there a built in method to apply the coupon to a stripe price id and get the result?

Example coupon is 99% off of $19.99.  I get this as being .19 cents, but on the stripe invoice it is .20 cents.

**Comment by brunogaspar** [comment]
Hey

Usually you create the coupon and set the percentage or amount to be discounted.

Then when you create either an invoice or an order, you can apply that coupon there. Don't think you need to perform any kind of calculation.

But give me more information on what you're trying to achieve so i can try to help you out a bit further.

**Comment by TheDoctorD** [comment]
So I have the user at a checkout page, that shows the price of the subscription.  I want to have them enter in a public facing promotion code such as SAVE50, have them apply it, and show them what they are going to save before checking out.

![Screenshot 2021-06-29 085401](https://user-images.githubusercontent.com/21107096/123809965-a8f25280-d8b7-11eb-90c2-bd6808b1aabb.png)

I didn't see anything about applying a coupon to a price before checking out.
I only saw the method to apply the coupon to a subscription when it gets created: 

$stripeSubscription = $user->newSubscription($product_title, $stripe_price_id)->withCoupon($subscription_product_coupon->coupon_stripe_id)->create($payment_method_token);

Thanks for any insight.

**Comment by brunogaspar** [comment]
That seems to be [Laravel Cashier](https://github.com/laravel/cashier-stripe) related code, so nothing to do with this integration or SDK.

But either way, i'm not sure that is currently possible on Stripe itself, unless you use their own checkout system, otherwise you need to perform these calculations yourself :)

Hope it helps.

**Comment by TheDoctorD** [comment]
Ah crap. Sorry!
