### ISSUE TITLE
v13.1.0 -> php8.0, but illuminate/support: ^8.0 isn't php8.0 compatible

### ISSUE THREAD

**Issue by abuenosvinos** [cartalyst/stripe-laravel#73]
Hi,

I saw that you made stripe-laravel compatible with php8.0, but in the composer.json you are using "illuminate/support": "^8.0", and this version is not compatible with php8.0, so, I can't use your package in php8.0 environments.

Is it possible to fix that?

Thanks for all!

Regards,
Antonio

**Comment by GrahamCampbell** [comment]
What? `illuminate/support` 6.x, 7.x, 8.x, and 9.x all work fine on PHP 8.0 (verified by automated testing).

**Comment by abuenosvinos** [comment]
In https://packagist.org/packages/illuminate/support#v8.0.0 you can see that illuminate/support works with php: ^7.3

And when I manage composer with stripe-laravel 13.1.0 I get that:
  Problem 1
    - Conclusion: don't install cartalyst/stripe-laravel v13.1.0 (conflict analysis result)
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.2) does not satisfy that requirement.

For sure the execution of the code in php8.0 works, but the problems are with the operations with composer because of the dependencies.

I hope I explained well.

Thanks!

**Comment by GrahamCampbell** [comment]
You're looking at the wrong version. See https://packagist.org/packages/illuminate/support#v8.58.0.

**Comment by abuenosvinos** [comment]
Ok Graham, so, there will be something in my project. I'll check.

Thanks for your support.
