### ISSUE TITLE
Your own checkout is throwing a 500

### ISSUE THREAD

**Issue by promanapeople** [cartalyst/stripe-laravel#74]
https://imgur.com/a/RZqpKGi

**Comment by brunogaspar** [comment]
And you decided to open an issue on an unrelated repository?

**Comment by promanapeople** [comment]
Yep. There doesn't appear to be a published support link (just social
media), and the only way to become a "member" (with presumption that it
will lead to the ability to actually get support) is to sign up, which
includes paying, which... doesn't work. Also the repo I'd like to access is
private, requiring... payment to access. You can see the problem with that,
I hope.

**Comment by suwardany** [comment]
@promanapeople the issue should be fixed. Feel free to email us for any further assistance.

**Comment by brunogaspar** [comment]
> There doesn't appear to be a published support link

@promanapeople There's a `Help & Support` link on the website (top right corner, click on the "hamburger" menu), which has the email address.

You should've used that instead of the GitHub issue tracker.
