### ISSUE TITLE
Verify source not working ?

### ISSUE THREAD

**Issue by sam-zed** [cartalyst/stripe-laravel#75]
### Your Environment

- OS and Version: Ubuntu 18
- PHP Version: 7.4
- Stripe Laravel Version: latest

### Expected behavior

VerifySource should work when provided 2 amounts

https://stripe.com/docs/api/customer_bank_accounts/verify

### Actual behavior

Undefined property: Cartalyst\Stripe\Stripe::$customers

### Steps to reproduce

```
$stripe->customers->verifySource(
  'cus_AJ6y81jMo1Na3p',
  'ba_1KOkJw2eZvKYlo2CktkSjLjD',
  ['amounts' => [32, 45]]
);
```

**Comment by brunogaspar** [comment]
Hi there @sam-zed 

The documentation you're linking is from the official Stripe API docs, and their documentation has examples of their official PHP SDK, therefore, that's why it does not work :)

Here's how you can do it with this library:

```php
$stripe->bankAccounts()->verify(
    'cus_AJ6y81jMo1Na3p', 
    'ba_1KOkJw2eZvKYlo2CktkSjLjD', 
    [32, 45]
);
```

Hope it helps :)

**Comment by mavrickdeveloper** [comment]
it helped indeed, thanks for your comment @brunogaspar

**Comment by brunogaspar** [comment]
Great! I'm going to close this one now, but feel free to reach out if you encounter any other problems :)
