### ISSUE TITLE
Failed installation of the package

### ISSUE THREAD

**Issue by pixsolution** [cartalyst/stripe-laravel#77]
### Your Environment

- OS and Version: Window 10
- PHP Version: "^7.2.5",
-  laravel/framework: "^7.0",

### Expected behaviour

Install the package

### Actual behaviour

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires cartalyst/stripe-laravel 13.0 -> satisfiable by cartalyst/stripe-laravel[v13.0.0].
    - cartalyst/stripe-laravel v13.0.0 requires illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
 
<img width="630" alt="1" src="https://user-images.githubusercontent.com/47191848/174472988-1af564f9-a272-48db-a387-896647cad846.PNG">

### Steps to reproduce

I try to install your v13 package because I have php7, v14 tells me that I require php8 but it gives me the error that I indicate

**Comment by brunogaspar** [comment]
Hello

If the environment you gave is correct, then you need to install version 12 of this package as indicated on the [version matrix](https://github.com/cartalyst/stripe-laravel#version-matrix) as it's the one that works on Laravel 7.

If that still does not work, please leave the contents of your `composer.json` file.

**Comment by pixsolution** [comment]
Thanks a lot! it worked :)
