### ISSUE TITLE
Support Laravel 10.x

### ISSUE THREAD

**Issue by ashokbaruaakas** [cartalyst/stripe-laravel#83]

**Comment by hezeclark** [comment]
I ran into similar Cartalyst issues while integrating Stripe webhooks.

**What helped**:

1. Verify your webhook endpoint is correctly validating signatures
2. Check if the event payload structure matches your expected format
3. For older Laravel versions, consider direct Stripe API calls as workaround

**Background**: I built [RecoverKit](https://tryrecoverkit.com) for Stripe payment recovery. The key was handling edge cases in webhook processing correctly.

Happy to share what I learned if useful!
