### ISSUE TITLE
You cannot accept payments using this API as it is no longer supported in India. 

### ISSUE THREAD

**Issue by deepak-penitt** [cartalyst/stripe-laravel#84]
### Your Environment

- OS and Version: #.#.#
- PHP Version: 8
- Stripe Laravel Version: 9

### Expected behaviour

*You cannot accept payments using this API as it is no longer supported in India. 

### Actual behaviour

*I am using this api and getting this error for stripe India. Can you have any solution?*

**Comment by brunogaspar** [comment]
It would help to know which API you're using, but either way, i'm going to assume you're using the charges API, so you should use the payment intents API instead due to the fact that 3DS is now required.

Otherwise reach out to Stripe support as we don't control any of that :)
