### ISSUE TITLE
Need Laravel 11 support

### ISSUE THREAD

**Issue by salimbt** [cartalyst/stripe-laravel#85]
### Your Environment

- OS and Version: #.#.#
- PHP Version: #.#.#
- Stripe Laravel Version: #.#.#

### Expected behaviour

*Please describe what you are expecting to see happening.*

### Actual behaviour

*Please describe what is actually happening.*

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

**Comment by brunogaspar** [comment]
v16 released
