### ISSUE TITLE
Update for guzzlehttp 6

### ISSUE THREAD

**Issue by evernest-com-au** [cartalyst/stripe-laravel#9]
On Laravel 5.1

Guzzlehttp 6 is the latest and stripe-laravel's dependency on 5 is stopping other packages being installed.

> php artisan clear-compiled
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove cartalyst/stripe-laravel v2.0.3
    - Conclusion: don't install cartalyst/stripe-laravel v2.0.0
    - Conclusion: don't install guzzlehttp/guzzle 6.0.2|install cartalyst/stripe-laravel v2.0.0
    - Conclusion: remove guzzlehttp/guzzle 5.3.0|install guzzlehttp/guzzle 6.0.2
    - Installation request for simplesoftwareio/simple-sms ^2.0 -> satisfiable by simplesoftwareio/simple-sms[2.0.0].
    - Conclusion: don't install cartalyst/stripe-laravel v2.0.2|install guzzlehttp/guzzle 6.0.2
    - Conclusion: don't install cartalyst/stripe-laravel v2.0.3|install guzzlehttp/guzzle 6.0.2
    - cartalyst/stripe-laravel v2.0.1 requires cartalyst/stripe 1.0.\* -> satisfiable by cartalyst/stripe[v1.0.3, v1.0.0, v1.0.1, v1.0.2].
    - cartalyst/stripe v1.0.3 requires guzzlehttp/guzzle ~5.2 -> satisfiable by guzzlehttp/guzzle[5.3.0, 5.2.0].
    - cartalyst/stripe v1.0.3 requires guzzlehttp/guzzle ~5.2 -> satisfiable by guzzlehttp/guzzle[5.3.0, 5.2.0].
    - cartalyst/stripe v1.0.2 requires guzzlehttp/guzzle ~5.2 -> satisfiable by guzzlehttp/guzzle[5.3.0, 5.2.0].
    - cartalyst/stripe v1.0.1 requires guzzlehttp/guzzle ~5.2 -> satisfiable by guzzlehttp/guzzle[5.3.0, 5.2.0].
    - cartalyst/stripe v1.0.0 requires guzzlehttp/guzzle ~5.2 -> satisfiable by guzzlehttp/guzzle[5.3.0, 5.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.2.0].
    - simplesoftwareio/simple-sms 2.0.0 requires guzzlehttp/guzzle ~6 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2].
    - Conclusion: don't install cartalyst/stripe-laravel v2.0.1|don't install guzzlehttp/guzzle 6.0.1|keep guzzlehttp/guzzle 5.3.0
    - Installation request for cartalyst/stripe-laravel 2.0.\* -> satisfiable by cartalyst/stripe-laravel[v2.0.0, v2.0.1, v2.0.2, v2.0.3].

**Comment by brunogaspar** [comment]
Guzzle 5 works fine on Laravel 5.1.

**Comment by evernest-com-au** [comment]
Sure. And so does 6.  Other packages are starting to require 6.

On Monday, September 7, 2015, Bruno Gaspar notifications@github.com wrote:

> Guzzle 5 works fine on Laravel 5.1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cartalyst/stripe-laravel/issues/9#issuecomment-138268888
> .

## 

Craig Read-Smith
www.jaksta.com
Jaksta Technologies Pty Ltd
US: +1 385 204 3878
AU: +61 409 448 342

**Comment by brunogaspar** [comment]
Right, i completely understand, but at the moment we have no time or man power to update this to Guzzle 6.

You can update it yourself and send a PR if you so desire.
